# Generated by Django 3.1.3 on 2021-09-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassesvariant',
            name='glasses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='glasses.glassesmodel'),
        ),
    ]
