# Generated by Django 3.1.3 on 2021-09-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0002_auto_20210923_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glassesvariant',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='3d/'),
        ),
    ]
