# Generated by Django 3.1.3 on 2021-11-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0003_auto_20210923_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraoption',
            old_name='cost',
            new_name='current_cost',
        ),
        migrations.RenameField(
            model_name='extraoption',
            old_name='cost_currency',
            new_name='current_cost_currency',
        ),
        migrations.RenameField(
            model_name='glassesmodel',
            old_name='cost',
            new_name='current_cost',
        ),
        migrations.RenameField(
            model_name='glassesmodel',
            old_name='cost_currency',
            new_name='current_cost_currency',
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='glassesmodel',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='3d/'),
        ),
        migrations.DeleteModel(
            name='GlassesVariant',
        ),
    ]
