# Generated by Django 3.2.7 on 2021-12-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasses', '0004_auto_20211104_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='glassesmodel',
            name='texture_file',
            field=models.FileField(blank=True, null=True, upload_to='textures/'),
        ),
    ]
